import { mount } from '@vue/test-utils'
import { describe, expect, it } from 'vitest'
import DebugHeaderChanges from '../DebugHeaderChanges.vue'

describe('DebugHeaderChanges', () => {
  it('labels every disposition and renders sensitive placeholder values as plain text', () => {
    const wrapper = mount(DebugHeaderChanges, { props: { changes: [
      { name: 'Accept-Language', action: 'preserved', input_values: ['zh-CN'], output_values: ['zh-CN'], reason: 'Allowed by gateway' },
      { name: 'Authorization', action: 'rewritten', input_values: ['[redacted]'], output_values: ['[redacted]'], reason: 'Account credentials' },
      { name: 'X-Client-Request-Id', action: 'generated', output_values: ['request-1'], reason: 'Generated by gateway' },
      { name: 'X-Unrecognized', action: 'filtered', input_values: ['<img src=x onerror=alert(1)>'], reason: 'Not allowed by gateway' }
    ] } })
    expect(wrapper.get('details').attributes('open')).toBeDefined()
    expect(wrapper.get('.change-legend').text()).toContain('保留 1')
    expect(wrapper.get('.change-legend').text()).toContain('重写 1')
    expect(wrapper.get('.change-legend').text()).toContain('生成 1')
    expect(wrapper.get('.change-legend').text()).toContain('过滤 1')
    expect(wrapper.find('img').exists()).toBe(false)
    expect(wrapper.text()).toContain('<img src=x onerror=alert(1)>')
  })
  it('does not claim recorded headers when no upstream request occurred', () => {
    const wrapper = mount(DebugHeaderChanges, { props: { changes: [] } })
    expect(wrapper.text()).toContain('尚无实际上游请求头记录')
    expect(wrapper.find('.header-change').exists()).toBe(false)
  })
})
